# Generated by Django 3.1.2 on 2021-03-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orthoepy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stressed', models.CharField(max_length=100, null=True)),
                ('name_stressed_wrong', models.CharField(max_length=100, null=True)),
                ('mistakes', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='punctuation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, null=True)),
                ('comma_pos', models.CharField(max_length=100, null=True)),
                ('mistakes', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='spelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_with_blanks', models.CharField(max_length=100, null=True)),
                ('mistakes', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
    ]
